spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bankdb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: bankuser
    password: nonmelaricordo
    driver-class-name: com.mysql.cj.jdbc.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
