spring:
  datasource:
    # Configurazione Supabase per i test di integrazione
    url: jdbc:postgresql://aws-1-eu-west-3.pooler.supabase.com:5432/postgres
    username: postgres.ehgsmaiqpbtpjiiqkpdx
    password: PestoProsciutto11!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create-drop
    properties:
      hibernate:
        default_schema: bank_schema_test
  liquibase:
    enabled: false
