version: "3.8"

volumes:
  data:
    driver: local

services:
  bank-db:
    platform: linux/amd64
    image: mysql:8.0
    container_name: bank-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: bankdb
      MYSQL_USER: bankuser
      MYSQL_PASSWORD: nonmelaricordo
    ports:
      - "3306:3306"
    volumes:
      - data:/database

